# DataSource configuration
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/auto_parc
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

  # JPA configuration
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
server:
  port: 3000